#!/usr/bin/env python3
"""Derive a scoped, plain-element LVS reference from design/netlist/lna.spice.

    python3 layout/lvs_reference.py layout/lna_core

Reads ``<cell-dir>/realization.json`` (which netlist instances the cell
draws, and with which PDK device) and writes
``<cell-dir>/<top>.lvs_reference.spice``: the in-scope subset of the design
netlist, one plain ``Q``/``M``/``R``/``C`` card per schematic instance, in
the class vocabulary klt's ``sg13g2`` extraction deck emits.

Why a derived reference beside the full-netlist compare: ``klt lvs`` is
also run against ``design/netlist/lna.spice`` itself (``lvs_full_request.json``)
and that compare cannot pair the two top circuits at all -- most of the
netlist is deliberately not drawn yet -- so it reports topology failures and
no per-device diagnosis. This reference restricts the compare to what was
drawn, so the remaining mismatches are about the drawn devices, not about
scope. It is a projection of the design netlist, never a hand-edited one:

* every in-scope instance keeps its own nodes and its own schematic value;
* the partition is exact -- every netlist instance must appear in exactly one
  of ``in_scope``/``out_of_scope`` in realization.json, or this script
  fails (a new netlist device cannot silently fall out of both);
* the only things taken from realization.json are the device *class* each
  ideal element is realized as (330 ohm -> ``rppd``, 100 pF -> ``cap_cmim``)
  and that realization's drawn geometry (``rppd`` L/W).
"""

from __future__ import annotations

import hashlib
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

#: PDK PyCell -> (SPICE element letter, klt sg13g2 extraction-deck class).
#: pmosHV/nmosHV: the deck reports thick-oxide MOS under the plain
#: ``pfet``/``nfet`` classes (its MOS flavour lives only in the --pdk model
#: binding, not the class name -- klt docs/cli/lvs.md), so HV-vs-LV is not
#: something this compare can see.
PCELL_CLASS = {
    "npn13G2": ("Q", "npn13G2"),
    "pmosHV": ("M", "pfet"),
    "nmosHV": ("M", "nfet"),
    "rppd": ("R", "rppd"),
    "cmim": ("C", "cap_cmim"),
}


def _um(value: str) -> str:
    """'1.005u' / '512u' -> '1.005U' (explicit micrometre suffix)."""
    v = value.strip().lower()
    if not v.endswith("u"):
        raise SystemExit(f"lvs_reference: expected a 'u'-suffixed length, got {value!r}")
    return v[:-1] + "U"


def _params(tokens: list[str]) -> dict[str, str]:
    out = {}
    for t in tokens:
        if "=" in t:
            k, v = t.split("=", 1)
            out[k.lower()] = v
    return out


def parse_netlist(path: Path) -> dict[str, list[str]]:
    cards: dict[str, list[str]] = {}
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("*") or line.startswith("."):
            continue
        toks = line.split()
        if toks[0] in cards:
            raise SystemExit(f"lvs_reference: duplicate instance {toks[0]}")
        cards[toks[0]] = toks
    return cards


def build(cell_dir: Path) -> Path:
    rz = json.loads((cell_dir / "realization.json").read_text())
    netlist = REPO / rz["netlist"]
    cards = parse_netlist(netlist)

    in_scope = rz["in_scope"]
    out_scope = rz["out_of_scope"]
    both = set(in_scope) & set(out_scope)
    missing = set(cards) - set(in_scope) - set(out_scope)
    stale = (set(in_scope) | set(out_scope)) - set(cards)
    if both or missing or stale:
        raise SystemExit(
            "lvs_reference: realization.json does not partition the netlist: "
            f"in both={sorted(both)} unassigned={sorted(missing)} not-in-netlist={sorted(stale)}"
        )

    sha = hashlib.sha256(netlist.read_bytes()).hexdigest()
    out_lines = [
        f"* {rz['top_cell']} LVS reference -- GENERATED by layout/lvs_reference.py; do not edit.",
        f"* source: {rz['netlist']} sha256:{sha}",
        f"* scope:  {cell_dir.name}/realization.json (in_scope: {', '.join(in_scope)})",
        "* Plain-element form, klt sg13g2 extraction-deck classes. Values are the",
        "* schematic's own; drawn geometry (rppd L/W) is the realization's.",
    ]
    for inst in cards:  # netlist order
        if inst not in in_scope:
            continue
        toks = cards[inst]
        spec = in_scope[inst]
        letter, cls = PCELL_CLASS[spec["pcell"]]
        name = letter + (inst[1:] if inst[0].upper() == "X" else inst)
        p = _params(toks)
        if letter == "Q":
            # XQn c b e s npn13G2 Nx=N  ->  Qn c b e s npn13G2 NE=N
            nodes = toks[1:5]
            out_lines.append(f"{name} {' '.join(nodes)} {cls} NE={int(p.get('nx', '1'))}")
        elif letter == "M":
            # XMn d g s b sg13_hv_pmos w= l= ng= m=  ->  Mn d g s b pfet L= W=
            nodes = toks[1:5]
            if int(p.get("m", "1")) != 1:
                raise SystemExit(f"lvs_reference: {inst}: m>1 not supported")
            out_lines.append(f"{name} {' '.join(nodes)} {cls} L={_um(p['l'])} W={_um(p['w'])}")
        elif letter == "R":
            # Rn a b <ohms> m=1  ->  Rn a b <ohms> rppd L= W=
            nodes, value = toks[1:3], toks[3]
            rp = spec["params"]
            out_lines.append(f"{name} {' '.join(nodes)} {value} {cls} L={_um(rp['l'])} W={_um(rp['w'])}")
        elif letter == "C":
            # Cn a b <farads> m=1  ->  Cn a b <farads> cap_cmim
            nodes, value = toks[1:3], toks[3]
            out_lines.append(f"{name} {' '.join(nodes)} {value.upper()} {cls}")
    out_lines.append(".END")
    out = cell_dir / f"{rz['top_cell']}.lvs_reference.spice"
    out.write_text("\n".join(out_lines) + "\n")
    return out


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(__doc__.split("\n\n")[1], file=sys.stderr)
        return 2
    out = build(Path(argv[1]).resolve())
    print(f"lvs_reference: wrote {out.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
